url: http://qingyuanht.com
baseurl: http://qingyuanht.com

title: 清远宏通
email: admin@qingyuanchina.com.cn
phone: +86 010-62152001
address: 北京市房山区长阳镇嘉州水郡225号5层1-512

collections:
  solutions:
    output: true




markdown: kramdown
permalink: pretty