url: http://qingyuanht.com/
baseurl: http://qingyuanht.com/

title: 清远宏通
email: admin@qingyuanchina.com.cn
phone: +86 010-62152001
address: 北京市海淀区中关村东路123号B座

collections:
  solutions:
    output: true




markdown: kramdown
permalink: pretty